name: enegia_ja
description: "Energia Já! - ODS 7: Energia Acessível e Limpa"
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  web_socket_channel: ^2.4.0
  uuid: ^4.3.3

  cupertino_icons: ^1.0.8
  flame: ^1.30.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/icons/icon_solar.png
    - assets/images/icons/icon_wind.png
    - assets/images/icons/icon_efficiency.png
    - assets/images/icons/icon_sanitation.png
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
